apiVersion: v1
kind: Secret
metadata:
  name: opensig-secrets
type: Opaque
data:
  # base64-encoded secrets (example values only)
  POSTGRES_DSN: cG9zdGdyZXM6Ly9vcGVuc2lnOm9wZW5zaWdAcG9zdGdyZXM6NTQzMi9vcGVuc2lnP3NzbG1vZGU9ZGlzYWJsZQ==
